// Code generated by mockgen. DO NOT EDIT.
package mock

import (
	"context"
	"reflect"

	"github.com/bpka/tps-pkb/internal/domain/entity"
	"github.com/bpka/tps-pkb/internal/domain/port"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// MockDendaRepository
type MockDendaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDendaRepositoryMockRecorder
}

type MockDendaRepositoryMockRecorder struct{ mock *MockDendaRepository }

func NewMockDendaRepository(ctrl *gomock.Controller) *MockDendaRepository {
	m := &MockDendaRepository{ctrl: ctrl}
	m.recorder = &MockDendaRepositoryMockRecorder{m}
	return m
}

func (m *MockDendaRepository) EXPECT() *MockDendaRepositoryMockRecorder { return m.recorder }

func (m *MockDendaRepository) FindByKewajibanID(ctx context.Context, kewajibanID uuid.UUID) ([]entity.Denda, error) {
	ret := m.ctrl.Call(m, "FindByKewajibanID", ctx, kewajibanID)
	ret0, _ := ret[0].([]entity.Denda)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDendaRepositoryMockRecorder) FindByKewajibanID(ctx, kewajibanID any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByKewajibanID", reflect.TypeOf((*MockDendaRepository)(nil).FindByKewajibanID), ctx, kewajibanID)
}

func (m *MockDendaRepository) FindByPembayaranID(ctx context.Context, pembayaranID uuid.UUID) ([]entity.Denda, error) {
	ret := m.ctrl.Call(m, "FindByPembayaranID", ctx, pembayaranID)
	ret0, _ := ret[0].([]entity.Denda)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDendaRepositoryMockRecorder) FindByPembayaranID(ctx, pembayaranID any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPembayaranID", reflect.TypeOf((*MockDendaRepository)(nil).FindByPembayaranID), ctx, pembayaranID)
}

// ensure interface compliance at compile time
var _ port.DendaRepository = (*MockDendaRepository)(nil)
