// Code generated by mockgen. DO NOT EDIT.
// Run `make generate` to regenerate after changing port/repository.go.
package mock

import (
	"context"
	"reflect"

	"github.com/bpka/tps-pkb/internal/domain/dto"
	"github.com/bpka/tps-pkb/internal/domain/entity"
	"github.com/bpka/tps-pkb/internal/domain/port"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"go.uber.org/mock/gomock"
)

// MockWajibPajakRepository
type MockWajibPajakRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWajibPajakRepositoryMockRecorder
}

type MockWajibPajakRepositoryMockRecorder struct{ mock *MockWajibPajakRepository }

func NewMockWajibPajakRepository(ctrl *gomock.Controller) *MockWajibPajakRepository {
	m := &MockWajibPajakRepository{ctrl: ctrl}
	m.recorder = &MockWajibPajakRepositoryMockRecorder{m}
	return m
}

func (m *MockWajibPajakRepository) EXPECT() *MockWajibPajakRepositoryMockRecorder { return m.recorder }

func (m *MockWajibPajakRepository) Save(ctx context.Context, wp *entity.WajibPajak) error {
	ret := m.ctrl.Call(m, "Save", ctx, wp)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockWajibPajakRepositoryMockRecorder) Save(ctx, wp any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockWajibPajakRepository)(nil).Save), ctx, wp)
}

func (m *MockWajibPajakRepository) Update(ctx context.Context, wp *entity.WajibPajak) error {
	ret := m.ctrl.Call(m, "Update", ctx, wp)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockWajibPajakRepositoryMockRecorder) Update(ctx, wp any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWajibPajakRepository)(nil).Update), ctx, wp)
}

func (m *MockWajibPajakRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.WajibPajak, error) {
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.WajibPajak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockWajibPajakRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWajibPajakRepository)(nil).FindByID), ctx, id)
}

func (m *MockWajibPajakRepository) FindAll(ctx context.Context, filter dto.WajibPajakFilter) ([]entity.WajibPajak, int, error) {
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]entity.WajibPajak)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockWajibPajakRepositoryMockRecorder) FindAll(ctx, filter any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockWajibPajakRepository)(nil).FindAll), ctx, filter)
}

func (m *MockWajibPajakRepository) ExistsByNIK(ctx context.Context, nik string) (bool, error) {
	ret := m.ctrl.Call(m, "ExistsByNIK", ctx, nik)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockWajibPajakRepositoryMockRecorder) ExistsByNIK(ctx, nik any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNIK", reflect.TypeOf((*MockWajibPajakRepository)(nil).ExistsByNIK), ctx, nik)
}

func (m *MockWajibPajakRepository) ExistsByNPWP(ctx context.Context, npwp string) (bool, error) {
	ret := m.ctrl.Call(m, "ExistsByNPWP", ctx, npwp)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockWajibPajakRepositoryMockRecorder) ExistsByNPWP(ctx, npwp any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByNPWP", reflect.TypeOf((*MockWajibPajakRepository)(nil).ExistsByNPWP), ctx, npwp)
}

// MockKewajibanRepository
type MockKewajibanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockKewajibanRepositoryMockRecorder
}

type MockKewajibanRepositoryMockRecorder struct{ mock *MockKewajibanRepository }

func NewMockKewajibanRepository(ctrl *gomock.Controller) *MockKewajibanRepository {
	m := &MockKewajibanRepository{ctrl: ctrl}
	m.recorder = &MockKewajibanRepositoryMockRecorder{m}
	return m
}

func (m *MockKewajibanRepository) EXPECT() *MockKewajibanRepositoryMockRecorder { return m.recorder }

func (m *MockKewajibanRepository) Save(ctx context.Context, k *entity.KewajibanPajak) error {
	ret := m.ctrl.Call(m, "Save", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockKewajibanRepositoryMockRecorder) Save(ctx, k any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockKewajibanRepository)(nil).Save), ctx, k)
}

func (m *MockKewajibanRepository) Update(ctx context.Context, k *entity.KewajibanPajak) error {
	ret := m.ctrl.Call(m, "Update", ctx, k)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockKewajibanRepositoryMockRecorder) Update(ctx, k any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockKewajibanRepository)(nil).Update), ctx, k)
}

func (m *MockKewajibanRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.KewajibanPajak, error) {
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.KewajibanPajak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockKewajibanRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockKewajibanRepository)(nil).FindByID), ctx, id)
}

func (m *MockKewajibanRepository) FindAll(ctx context.Context, filter dto.KewajibanFilter) ([]entity.KewajibanPajak, int, error) {
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]entity.KewajibanPajak)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockKewajibanRepositoryMockRecorder) FindAll(ctx, filter any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockKewajibanRepository)(nil).FindAll), ctx, filter)
}

// MockPembayaranRepository
type MockPembayaranRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPembayaranRepositoryMockRecorder
}

type MockPembayaranRepositoryMockRecorder struct{ mock *MockPembayaranRepository }

func NewMockPembayaranRepository(ctrl *gomock.Controller) *MockPembayaranRepository {
	m := &MockPembayaranRepository{ctrl: ctrl}
	m.recorder = &MockPembayaranRepositoryMockRecorder{m}
	return m
}

func (m *MockPembayaranRepository) EXPECT() *MockPembayaranRepositoryMockRecorder { return m.recorder }

func (m *MockPembayaranRepository) SaveWithDenda(ctx context.Context, p *entity.Pembayaran, dendaList []entity.Denda, newTotal decimal.Decimal, newStatus entity.StatusKewajiban) error {
	ret := m.ctrl.Call(m, "SaveWithDenda", ctx, p, dendaList, newTotal, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockPembayaranRepositoryMockRecorder) SaveWithDenda(ctx, p, dendaList, newTotal, newStatus any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWithDenda", reflect.TypeOf((*MockPembayaranRepository)(nil).SaveWithDenda), ctx, p, dendaList, newTotal, newStatus)
}

func (m *MockPembayaranRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Pembayaran, error) {
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Pembayaran)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPembayaranRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPembayaranRepository)(nil).FindByID), ctx, id)
}

// MockAuditService
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
}

type MockAuditServiceMockRecorder struct{ mock *MockAuditService }

func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	m := &MockAuditService{ctrl: ctrl}
	m.recorder = &MockAuditServiceMockRecorder{m}
	return m
}

func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder { return m.recorder }

func (m *MockAuditService) Log(ctx context.Context, entry port.AuditEntry) error {
	ret := m.ctrl.Call(m, "Log", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockAuditServiceMockRecorder) Log(ctx, entry any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockAuditService)(nil).Log), ctx, entry)
}
