// Code generated by mockgen. DO NOT EDIT.
// Run `make generate` to regenerate after changing port/service.go.
package mock

import (
	"context"
	"reflect"

	"github.com/bpka/tps-pkb/internal/domain/dto"
	"github.com/bpka/tps-pkb/internal/domain/entity"
	"github.com/google/uuid"
	"go.uber.org/mock/gomock"
)

// MockAuthService is a mock of port.AuthService.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

type MockAuthServiceMockRecorder struct{ mock *MockAuthService }

func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	m := &MockAuthService{ctrl: ctrl}
	m.recorder = &MockAuthServiceMockRecorder{m}
	return m
}

func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder { return m.recorder }

func (m *MockAuthService) Login(ctx context.Context, req dto.LoginRequest) (*dto.TokenResponse, error) {
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(*dto.TokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockAuthServiceMockRecorder) Login(ctx, req any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, req)
}

// MockWajibPajakService is a mock of port.WajibPajakService.
type MockWajibPajakService struct {
	ctrl     *gomock.Controller
	recorder *MockWajibPajakServiceMockRecorder
}

type MockWajibPajakServiceMockRecorder struct{ mock *MockWajibPajakService }

func NewMockWajibPajakService(ctrl *gomock.Controller) *MockWajibPajakService {
	m := &MockWajibPajakService{ctrl: ctrl}
	m.recorder = &MockWajibPajakServiceMockRecorder{m}
	return m
}

func (m *MockWajibPajakService) EXPECT() *MockWajibPajakServiceMockRecorder { return m.recorder }

func (m *MockWajibPajakService) Create(ctx context.Context, req dto.CreateWajibPajakRequest) (*entity.WajibPajak, error) {
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*entity.WajibPajak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockWajibPajakServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWajibPajakService)(nil).Create), ctx, req)
}

func (m *MockWajibPajakService) List(ctx context.Context, filter dto.WajibPajakFilter) ([]entity.WajibPajak, int, error) {
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]entity.WajibPajak)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockWajibPajakServiceMockRecorder) List(ctx, filter any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWajibPajakService)(nil).List), ctx, filter)
}

func (m *MockWajibPajakService) GetByID(ctx context.Context, id uuid.UUID) (*entity.WajibPajak, error) {
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.WajibPajak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockWajibPajakServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockWajibPajakService)(nil).GetByID), ctx, id)
}

func (m *MockWajibPajakService) Update(ctx context.Context, id uuid.UUID, req dto.UpdateWajibPajakRequest) (*entity.WajibPajak, error) {
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*entity.WajibPajak)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockWajibPajakServiceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWajibPajakService)(nil).Update), ctx, id, req)
}

func (m *MockWajibPajakService) SetActive(ctx context.Context, id uuid.UUID, active bool) error {
	ret := m.ctrl.Call(m, "SetActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockWajibPajakServiceMockRecorder) SetActive(ctx, id, active any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockWajibPajakService)(nil).SetActive), ctx, id, active)
}

// MockPembayaranService is a mock of port.PembayaranService.
type MockPembayaranService struct {
	ctrl     *gomock.Controller
	recorder *MockPembayaranServiceMockRecorder
}

type MockPembayaranServiceMockRecorder struct{ mock *MockPembayaranService }

func NewMockPembayaranService(ctrl *gomock.Controller) *MockPembayaranService {
	m := &MockPembayaranService{ctrl: ctrl}
	m.recorder = &MockPembayaranServiceMockRecorder{m}
	return m
}

func (m *MockPembayaranService) EXPECT() *MockPembayaranServiceMockRecorder { return m.recorder }

func (m *MockPembayaranService) Create(ctx context.Context, req dto.CreatePembayaranRequest, userID uuid.UUID) (*entity.Pembayaran, []entity.Denda, error) {
	ret := m.ctrl.Call(m, "Create", ctx, req, userID)
	ret0, _ := ret[0].(*entity.Pembayaran)
	ret1, _ := ret[1].([]entity.Denda)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockPembayaranServiceMockRecorder) Create(ctx, req, userID any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPembayaranService)(nil).Create), ctx, req, userID)
}

// MockDendaService is a mock of port.DendaService.
type MockDendaService struct {
	ctrl     *gomock.Controller
	recorder *MockDendaServiceMockRecorder
}

type MockDendaServiceMockRecorder struct{ mock *MockDendaService }

func NewMockDendaService(ctrl *gomock.Controller) *MockDendaService {
	m := &MockDendaService{ctrl: ctrl}
	m.recorder = &MockDendaServiceMockRecorder{m}
	return m
}

func (m *MockDendaService) EXPECT() *MockDendaServiceMockRecorder { return m.recorder }

func (m *MockDendaService) Hitung(input dto.DendaInput) []entity.Denda {
	ret := m.ctrl.Call(m, "Hitung", input)
	ret0, _ := ret[0].([]entity.Denda)
	return ret0
}

func (mr *MockDendaServiceMockRecorder) Hitung(input any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hitung", reflect.TypeOf((*MockDendaService)(nil).Hitung), input)
}

func (m *MockDendaService) GetByKewajibanID(ctx context.Context, id uuid.UUID) ([]entity.Denda, error) {
	ret := m.ctrl.Call(m, "GetByKewajibanID", ctx, id)
	ret0, _ := ret[0].([]entity.Denda)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDendaServiceMockRecorder) GetByKewajibanID(ctx, id any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKewajibanID", reflect.TypeOf((*MockDendaService)(nil).GetByKewajibanID), ctx, id)
}
